"""
Task 24: smoke tests proving the de-identified fixture lab reports
(tests/fixtures/lab_reports/, generated by
tests/fixtures/generate_lab_report_fixtures.py) actually work as input
to the real pipeline pieces that don't need a live paid API: PDF/image
loading (app/ocr/image_utils.py) and the real local Tesseract OCR
engine (app/ocr/tesseract_provider.py) - no network, no API key,
same "runs for real" pattern as test_ocr_provider_shape.py.

AI extraction itself is NOT exercised here - that needs a real,
billed Claude call, which is exactly what these tests must never make
(see test_ai_extraction.py for the mocked version of that). These
tests only prove the fixtures are usable, well-formed pipeline input.
"""

from pathlib import Path

from app.ocr.image_utils import load_image_pages
from app.ocr.tesseract_provider import TesseractProvider

FIXTURES_DIR = Path(__file__).parent / "fixtures" / "lab_reports"


def _read(filename: str) -> bytes:
    return (FIXTURES_DIR / filename).read_bytes()


def _all_word_text(result) -> str:
    return " ".join(word.text for word in result.words)


def test_all_five_fixture_files_exist():
    expected = {
        "clear.png",
        "blurry.png",
        "rotated.png",
        "multi_page.pdf",
        "unusual_layout.png",
    }
    actual = {path.name for path in FIXTURES_DIR.iterdir()}
    assert expected <= actual


def test_clear_fixture_ocrs_cleanly_with_real_tesseract():
    result = TesseractProvider().extract(_read("clear.png"))

    assert len(result.words) > 0
    text = _all_word_text(result).lower()
    assert "hemoglobin" in text
    assert "glucose" in text


def test_blurry_fixture_still_produces_a_valid_ocr_result():
    # Blur degrades accuracy - the point of this fixture is verifying
    # the pipeline handles a poor-quality scan gracefully (a valid,
    # possibly-sparse OcrResult), not that OCR reads it perfectly.
    result = TesseractProvider().extract(_read("blurry.png"))

    assert isinstance(result.words, list)
    for word in result.words:
        assert 0.0 <= word.confidence <= 1.0


def test_rotated_fixture_still_produces_a_valid_ocr_result():
    result = TesseractProvider().extract(_read("rotated.png"))

    assert isinstance(result.words, list)
    for word in result.words:
        assert word.page_number == 1


def test_unusual_layout_fixture_ocrs_cleanly_with_real_tesseract():
    result = TesseractProvider().extract(_read("unusual_layout.png"))

    assert len(result.words) > 0
    text = _all_word_text(result).lower()
    assert "hemoglobin" in text


def test_multi_page_fixture_loads_as_two_separate_pages():
    pages = load_image_pages(_read("multi_page.pdf"))

    assert len(pages) == 2


def test_multi_page_fixture_ocrs_with_words_tagged_to_the_right_page():
    result = TesseractProvider().extract(_read("multi_page.pdf"))

    page_numbers = {word.page_number for word in result.words}
    assert page_numbers == {1, 2}

    page_one_text = " ".join(
        word.text for word in result.words if word.page_number == 1
    ).lower()
    page_two_text = " ".join(
        word.text for word in result.words if word.page_number == 2
    ).lower()
    # Page 1 is the hematology panel, page 2 is chemistry - proving
    # words are tagged to the page they actually came from, not just
    # concatenated.
    assert "hemoglobin" in page_one_text
    assert "glucose" in page_two_text
