"""audit log append only trigger

This can't be generated by `alembic revision --autogenerate` - our
SQLAlchemy models describe TABLES and COLUMNS, but a database TRIGGER
isn't something a Python model can express, so this migration is
written by hand instead.

What it does: makes Postgres itself refuse any UPDATE or DELETE on the
audit_log table. Application code (app/core/audit.py) already never
tries to update or delete a row - this is the belt-and-suspenders
version, enforced by the database, so even a bug (or someone with a raw
SQL console) can't quietly rewrite audit history.

Revision ID: 58984b0977b6
Revises: 0c36bed19775
Create Date: 2026-08-04 19:30:42.972634

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58984b0977b6"
down_revision: Union[str, None] = "0c36bed19775"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE OR REPLACE FUNCTION prevent_audit_log_modification()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION
                'audit_log is append-only: % is not allowed', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_append_only
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION prevent_audit_log_modification();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_log_append_only ON audit_log;")
    op.execute("DROP FUNCTION IF EXISTS prevent_audit_log_modification();")
