"""ocr evidence tables

Adds `ocr_words` (one row per word OCR read off a report - the raw
evidence trail) and `result_ocr_words` (a many-to-many join table
linking a future extracted result to the exact OCR word(s) it came
from - not written to yet, since AI extraction doesn't exist).

Auto-generated from the SQLAlchemy models in app/models/ocr_word.py and
app/models/result_ocr_word.py (see the Task summary for the
scratch-Postgres run that applied and verified this).

Revision ID: d4f4dd90ffca
Revises: 58984b0977b6
Create Date: 2026-08-07 18:00:50.903089

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4f4dd90ffca"
down_revision: Union[str, None] = "58984b0977b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ocr_words",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("word_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("confidence", sa.Numeric(), nullable=False),
        sa.Column(
            "bounding_box", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("ocr_provider", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ocr_words_report_id"), "ocr_words", ["report_id"], unique=False
    )
    op.create_table(
        "result_ocr_words",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("result_id", sa.UUID(), nullable=False),
        sa.Column("ocr_word_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["ocr_word_id"], ["ocr_words.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["result_id"], ["results.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_result_ocr_words_ocr_word_id"),
        "result_ocr_words",
        ["ocr_word_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_result_ocr_words_result_id"),
        "result_ocr_words",
        ["result_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_result_ocr_words_result_id"), table_name="result_ocr_words")
    op.drop_index(
        op.f("ix_result_ocr_words_ocr_word_id"), table_name="result_ocr_words"
    )
    op.drop_table("result_ocr_words")
    op.drop_index(op.f("ix_ocr_words_report_id"), table_name="ocr_words")
    op.drop_table("ocr_words")
    # ### end Alembic commands ###
