"""ai extraction columns

Adds the columns AI extraction (app/ai/) writes to: per-result fields
on `results` (canonical_test_name, result_date, lab_name,
ai_confidence, and job_id for traceability), and per-report
prompt/model traceability fields on `reports` (extraction_model,
extraction_prompt_version).

Auto-generated from the SQLAlchemy models in app/models/result.py and
app/models/report.py (see the Task summary for the scratch-Postgres run
that applied and verified this). The foreign key's autogenerated `None`
name was replaced with an explicit one so downgrade() can actually
drop it by name.

Revision ID: efd579912105
Revises: d4f4dd90ffca
Create Date: 2026-08-07 19:10:23.039627

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efd579912105"
down_revision: Union[str, None] = "d4f4dd90ffca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reports", sa.Column("extraction_model", sa.String(), nullable=True))
    op.add_column(
        "reports", sa.Column("extraction_prompt_version", sa.String(), nullable=True)
    )
    op.add_column("results", sa.Column("job_id", sa.UUID(), nullable=True))
    op.add_column(
        "results", sa.Column("canonical_test_name", sa.String(), nullable=True)
    )
    op.add_column("results", sa.Column("result_date", sa.String(), nullable=True))
    op.add_column("results", sa.Column("lab_name", sa.String(), nullable=True))
    op.add_column("results", sa.Column("ai_confidence", sa.Numeric(), nullable=True))
    op.create_foreign_key(
        "fk_results_job_id_jobs",
        "results",
        "jobs",
        ["job_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_results_job_id_jobs", "results", type_="foreignkey")
    op.drop_column("results", "ai_confidence")
    op.drop_column("results", "lab_name")
    op.drop_column("results", "result_date")
    op.drop_column("results", "canonical_test_name")
    op.drop_column("results", "job_id")
    op.drop_column("reports", "extraction_prompt_version")
    op.drop_column("reports", "extraction_model")
    # ### end Alembic commands ###
