"""
Task 24: generates the de-identified sample lab report fixtures used to
exercise the whole pipeline (OCR -> extraction -> trust chain -> ...)
against realistic-shaped input, without ever using real patient data.

Every fixture is entirely FABRICATED: a fake lab name, a fake patient
label, and fake (but plausible-looking) test values, all generated by
this script - there is no real report or real person behind any of
them. Every image is stamped with a visible
"SYNTHETIC SAMPLE - NOT A REAL PATIENT" banner for extra clarity.

Produces, into tests/fixtures/lab_reports/:
  clear.png              - a clean, straightforward table layout
  blurry.png              - the same report, Gaussian-blurred (a shaky photo)
  rotated.png              - the same report, rotated ~7 degrees (a skewed photo)
  multi_page.pdf            - a 2-page report (hematology, then chemistry panels)
  unusual_layout.png        - a non-tabular, inline-label layout
  high_res_full_panel.png   - a large, high-resolution, easy-to-OCR report with
                             an 11-test spread across three panels, including
                             both High and Low flagged values (everything above
                             is deliberately in-range, so this is the one to use
                             for exercising the full range of status badges)

Regenerate with:

    python -m tests.fixtures.generate_lab_report_fixtures

These are checked-in binary fixtures (not regenerated on every test
run) so the pipeline tests in test_pipeline_fixtures.py have stable,
reviewable input.
"""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont

FIXTURES_DIR = Path(__file__).parent / "lab_reports"

_FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
_FONT_BOLD_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"


def _font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    try:
        return ImageFont.truetype(_FONT_BOLD_PATH if bold else _FONT_PATH, size)
    except OSError:
        return ImageFont.load_default(size=size)


# Fabricated data only - no real test results, no real patient, no real
# lab. Structured as (test, value, unit, reference_range) purely for
# fixture layout purposes; nothing here is read by app code.
_HEMATOLOGY_PANEL = [
    ("Hemoglobin", "13.5", "g/dL", "12.0-15.5"),
    ("White Blood Cell Count", "6.8", "x10^3/uL", "4.0-11.0"),
    ("Platelet Count", "250", "x10^3/uL", "150-400"),
]
_CHEMISTRY_PANEL = [
    ("Glucose", "95", "mg/dL", "70-100"),
    ("Total Cholesterol", "180", "mg/dL", "125-200"),
    ("Creatinine", "0.9", "mg/dL", "0.6-1.3"),
]

# For high_res_full_panel.png: a wider, three-section spread with
# DELIBERATE out-of-range values (unlike the panels above, which are
# all in-range) so the results screen's High/Low/Normal status badges
# all have something real to show. Still entirely fabricated.
_FULL_PANEL_SECTIONS = [
    (
        "Complete Blood Count (CBC)",
        [
            ("Hemoglobin", "10.1", "g/dL", "12.0-15.5"),  # Low
            ("White Blood Cell Count", "12.6", "x10^3/uL", "4.0-11.0"),  # High
            ("Platelet Count", "265", "x10^3/uL", "150-400"),
            ("Hematocrit", "38.2", "%", "36.0-46.0"),
        ],
    ),
    (
        "Basic Metabolic Panel",
        [
            ("Glucose", "112", "mg/dL", "70-100"),  # High
            ("Sodium", "139", "mmol/L", "135-145"),
            ("Potassium", "4.1", "mmol/L", "3.5-5.1"),
            ("Creatinine", "0.85", "mg/dL", "0.6-1.3"),
            ("BUN", "15", "mg/dL", "7-20"),
        ],
    ),
    (
        "Lipid Panel",
        [
            ("Total Cholesterol", "205", "mg/dL", "125-200"),  # High
            ("HDL Cholesterol", "38", "mg/dL", "40-60"),  # Low
        ],
    ),
]


def _draw_banner(draw: ImageDraw.ImageDraw, width: int) -> None:
    draw.rectangle([(0, 0), (width, 26)], fill=(255, 230, 150))
    draw.text(
        (10, 5),
        "SYNTHETIC SAMPLE - NOT A REAL PATIENT",
        fill=(120, 60, 0),
        font=_font(14, bold=True),
    )


def _draw_table_report(panel: list[tuple[str, str, str, str]]) -> Image.Image:
    width, height = 900, 140 + 40 * len(panel)
    image = Image.new("RGB", (width, height), color="white")
    draw = ImageDraw.Draw(image)
    _draw_banner(draw, width)

    draw.text(
        (10, 40),
        "Fixture Regional Lab (Synthetic Data)",
        font=_font(20, bold=True),
        fill="black",
    )
    draw.text(
        (10, 68),
        "Patient: SAMPLE PATIENT   Fixture ID: SAMPLE-0001",
        font=_font(14),
        fill="black",
    )
    draw.text((10, 88), "Report Date: 2026-01-01", font=_font(14), fill="black")

    header_y = 118
    columns = [("Test", 10), ("Result", 400), ("Unit", 520), ("Reference Range", 650)]
    for label, x in columns:
        draw.text((x, header_y), label, font=_font(14, bold=True), fill="black")
    draw.line([(10, header_y + 22), (width - 10, header_y + 22)], fill="black", width=1)

    row_y = header_y + 32
    for test, value, unit, ref_range in panel:
        draw.text((10, row_y), test, font=_font(14), fill="black")
        draw.text((400, row_y), value, font=_font(14), fill="black")
        draw.text((520, row_y), unit, font=_font(14), fill="black")
        draw.text((650, row_y), ref_range, font=_font(14), fill="black")
        row_y += 40

    return image


def _draw_unusual_layout_report() -> Image.Image:
    # A report that doesn't use a table at all: inline "Label: value
    # unit (range)" lines in two columns, mimicking a lab whose
    # template is nothing like the standard grid.
    width, height = 900, 420
    image = Image.new("RGB", (width, height), color="white")
    draw = ImageDraw.Draw(image)
    _draw_banner(draw, width)

    draw.text(
        (10, 40),
        "*** FIXTURE DIAGNOSTIC CENTER - SAMPLE REPORT ***",
        font=_font(18, bold=True),
        fill="black",
    )
    draw.text(
        (10, 68),
        "Sample Patient // Fixture ID SAMPLE-0002 // Collected 2026-02-14",
        font=_font(13),
        fill="black",
    )

    all_rows = _HEMATOLOGY_PANEL + _CHEMISTRY_PANEL
    left_column = all_rows[: len(all_rows) // 2 + 1]
    right_column = all_rows[len(all_rows) // 2 + 1 :]

    y = 110
    for test, value, unit, ref_range in left_column:
        draw.text(
            (20, y),
            f"{test}: {value} {unit} [normal: {ref_range}]",
            font=_font(15),
            fill="black",
        )
        y += 34

    y = 110
    for test, value, unit, ref_range in right_column:
        draw.text(
            (470, y),
            f"{test} = {value} {unit} (ref {ref_range})",
            font=_font(15),
            fill="black",
        )
        y += 34

    draw.text(
        (20, 360),
        "-- end of synthetic sample report --",
        font=_font(12),
        fill=(100, 100, 100),
    )
    return image


def _draw_high_res_full_panel_report() -> Image.Image:
    # Roughly a US-letter page at 200 DPI (8.5in x 11in) - large enough
    # that every character is unambiguous to OCR, unlike the 900px-wide
    # fixtures above which are deliberately modest-resolution.
    width = 1700
    row_count = sum(len(rows) for _, rows in _FULL_PANEL_SECTIONS)
    section_count = len(_FULL_PANEL_SECTIONS)
    height = 420 + row_count * 78 + section_count * 90

    image = Image.new("RGB", (width, height), color="white")
    draw = ImageDraw.Draw(image)

    draw.rectangle([(0, 0), (width, 56)], fill=(255, 230, 150))
    draw.text(
        (24, 12),
        "SYNTHETIC SAMPLE - NOT A REAL PATIENT",
        fill=(120, 60, 0),
        font=_font(30, bold=True),
    )

    draw.text(
        (24, 90),
        "Fixture Regional Lab (Synthetic Data)",
        font=_font(44, bold=True),
        fill="black",
    )
    draw.text(
        (24, 150),
        "Patient: SAMPLE PATIENT   Fixture ID: SAMPLE-0003",
        font=_font(28),
        fill="black",
    )
    draw.text((24, 188), "Report Date: 2026-03-15", font=_font(28), fill="black")

    columns = [("Test", 24), ("Result", 940), ("Unit", 1160), ("Reference Range", 1360)]

    y = 260
    for section_title, rows in _FULL_PANEL_SECTIONS:
        draw.text((24, y), section_title, font=_font(32, bold=True), fill=(40, 60, 40))
        y += 44
        for label, x in columns:
            draw.text((x, y), label, font=_font(26, bold=True), fill="black")
        y += 36
        draw.line([(24, y), (width - 24, y)], fill="black", width=2)
        y += 14

        for test, value, unit, ref_range in rows:
            draw.text((24, y), test, font=_font(28), fill="black")
            draw.text((940, y), value, font=_font(28, bold=True), fill="black")
            draw.text((1160, y), unit, font=_font(28), fill="black")
            draw.text((1360, y), ref_range, font=_font(28), fill="black")
            y += 56
        y += 46

    return image


def generate_all_fixtures() -> None:
    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)

    full_panel = _HEMATOLOGY_PANEL + _CHEMISTRY_PANEL

    clear = _draw_table_report(full_panel)
    clear.save(FIXTURES_DIR / "clear.png")

    blurry = clear.filter(ImageFilter.GaussianBlur(radius=2.2))
    blurry.save(FIXTURES_DIR / "blurry.png")

    rotated = clear.rotate(7, expand=True, fillcolor="white")
    rotated.save(FIXTURES_DIR / "rotated.png")

    page_one = _draw_table_report(_HEMATOLOGY_PANEL)
    page_two = _draw_table_report(_CHEMISTRY_PANEL)
    page_one.save(
        FIXTURES_DIR / "multi_page.pdf",
        "PDF",
        resolution=100.0,
        save_all=True,
        append_images=[page_two],
    )

    unusual = _draw_unusual_layout_report()
    unusual.save(FIXTURES_DIR / "unusual_layout.png")

    high_res_full_panel = _draw_high_res_full_panel_report()
    high_res_full_panel.save(FIXTURES_DIR / "high_res_full_panel.png")


if __name__ == "__main__":
    generate_all_fixtures()
    print(f"Generated fixtures in {FIXTURES_DIR}")
