"""
Task 24: generates the de-identified sample lab report fixtures used to
exercise the whole pipeline (OCR -> extraction -> trust chain -> ...)
against realistic-shaped input, without ever using real patient data.

Every fixture is entirely FABRICATED: a fake lab name, a fake patient
label, and fake (but plausible-looking) test values, all generated by
this script - there is no real report or real person behind any of
them. Every image is stamped with a visible
"SYNTHETIC SAMPLE - NOT A REAL PATIENT" banner for extra clarity.

Produces, into tests/fixtures/lab_reports/:
  clear.png         - a clean, straightforward table layout
  blurry.png         - the same report, Gaussian-blurred (a shaky photo)
  rotated.png         - the same report, rotated ~7 degrees (a skewed photo)
  multi_page.pdf       - a 2-page report (hematology, then chemistry panels)
  unusual_layout.png   - a non-tabular, inline-label layout

Regenerate with:

    python -m tests.fixtures.generate_lab_report_fixtures

These are checked-in binary fixtures (not regenerated on every test
run) so the pipeline tests in test_pipeline_fixtures.py have stable,
reviewable input.
"""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont

FIXTURES_DIR = Path(__file__).parent / "lab_reports"

_FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
_FONT_BOLD_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"


def _font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    try:
        return ImageFont.truetype(_FONT_BOLD_PATH if bold else _FONT_PATH, size)
    except OSError:
        return ImageFont.load_default(size=size)


# Fabricated data only - no real test results, no real patient, no real
# lab. Structured as (test, value, unit, reference_range) purely for
# fixture layout purposes; nothing here is read by app code.
_HEMATOLOGY_PANEL = [
    ("Hemoglobin", "13.5", "g/dL", "12.0-15.5"),
    ("White Blood Cell Count", "6.8", "x10^3/uL", "4.0-11.0"),
    ("Platelet Count", "250", "x10^3/uL", "150-400"),
]
_CHEMISTRY_PANEL = [
    ("Glucose", "95", "mg/dL", "70-100"),
    ("Total Cholesterol", "180", "mg/dL", "125-200"),
    ("Creatinine", "0.9", "mg/dL", "0.6-1.3"),
]


def _draw_banner(draw: ImageDraw.ImageDraw, width: int) -> None:
    draw.rectangle([(0, 0), (width, 26)], fill=(255, 230, 150))
    draw.text(
        (10, 5),
        "SYNTHETIC SAMPLE - NOT A REAL PATIENT",
        fill=(120, 60, 0),
        font=_font(14, bold=True),
    )


def _draw_table_report(panel: list[tuple[str, str, str, str]]) -> Image.Image:
    width, height = 900, 140 + 40 * len(panel)
    image = Image.new("RGB", (width, height), color="white")
    draw = ImageDraw.Draw(image)
    _draw_banner(draw, width)

    draw.text(
        (10, 40),
        "Fixture Regional Lab (Synthetic Data)",
        font=_font(20, bold=True),
        fill="black",
    )
    draw.text(
        (10, 68),
        "Patient: SAMPLE PATIENT   Fixture ID: SAMPLE-0001",
        font=_font(14),
        fill="black",
    )
    draw.text((10, 88), "Report Date: 2026-01-01", font=_font(14), fill="black")

    header_y = 118
    columns = [("Test", 10), ("Result", 400), ("Unit", 520), ("Reference Range", 650)]
    for label, x in columns:
        draw.text((x, header_y), label, font=_font(14, bold=True), fill="black")
    draw.line([(10, header_y + 22), (width - 10, header_y + 22)], fill="black", width=1)

    row_y = header_y + 32
    for test, value, unit, ref_range in panel:
        draw.text((10, row_y), test, font=_font(14), fill="black")
        draw.text((400, row_y), value, font=_font(14), fill="black")
        draw.text((520, row_y), unit, font=_font(14), fill="black")
        draw.text((650, row_y), ref_range, font=_font(14), fill="black")
        row_y += 40

    return image


def _draw_unusual_layout_report() -> Image.Image:
    # A report that doesn't use a table at all: inline "Label: value
    # unit (range)" lines in two columns, mimicking a lab whose
    # template is nothing like the standard grid.
    width, height = 900, 420
    image = Image.new("RGB", (width, height), color="white")
    draw = ImageDraw.Draw(image)
    _draw_banner(draw, width)

    draw.text(
        (10, 40),
        "*** FIXTURE DIAGNOSTIC CENTER - SAMPLE REPORT ***",
        font=_font(18, bold=True),
        fill="black",
    )
    draw.text(
        (10, 68),
        "Sample Patient // Fixture ID SAMPLE-0002 // Collected 2026-02-14",
        font=_font(13),
        fill="black",
    )

    all_rows = _HEMATOLOGY_PANEL + _CHEMISTRY_PANEL
    left_column = all_rows[: len(all_rows) // 2 + 1]
    right_column = all_rows[len(all_rows) // 2 + 1 :]

    y = 110
    for test, value, unit, ref_range in left_column:
        draw.text(
            (20, y),
            f"{test}: {value} {unit} [normal: {ref_range}]",
            font=_font(15),
            fill="black",
        )
        y += 34

    y = 110
    for test, value, unit, ref_range in right_column:
        draw.text(
            (470, y),
            f"{test} = {value} {unit} (ref {ref_range})",
            font=_font(15),
            fill="black",
        )
        y += 34

    draw.text(
        (20, 360),
        "-- end of synthetic sample report --",
        font=_font(12),
        fill=(100, 100, 100),
    )
    return image


def generate_all_fixtures() -> None:
    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)

    full_panel = _HEMATOLOGY_PANEL + _CHEMISTRY_PANEL

    clear = _draw_table_report(full_panel)
    clear.save(FIXTURES_DIR / "clear.png")

    blurry = clear.filter(ImageFilter.GaussianBlur(radius=2.2))
    blurry.save(FIXTURES_DIR / "blurry.png")

    rotated = clear.rotate(7, expand=True, fillcolor="white")
    rotated.save(FIXTURES_DIR / "rotated.png")

    page_one = _draw_table_report(_HEMATOLOGY_PANEL)
    page_two = _draw_table_report(_CHEMISTRY_PANEL)
    page_one.save(
        FIXTURES_DIR / "multi_page.pdf",
        "PDF",
        resolution=100.0,
        save_all=True,
        append_images=[page_two],
    )

    unusual = _draw_unusual_layout_report()
    unusual.save(FIXTURES_DIR / "unusual_layout.png")


if __name__ == "__main__":
    generate_all_fixtures()
    print(f"Generated fixtures in {FIXTURES_DIR}")
